version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "ContactManagementDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Admin*123"

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postech.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin*123"
    depends_on:
      - db
    links:
      - db:postgres

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Admin*123"
    labels:
      - "rabbitmq.version=3-management"

