version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: "ContactManagementDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Admin*123"
    networks:
      techchallenge-postech-4nett-fasetres-worker-persistency_custom_network:
        ipv4_address: 192.168.80.5
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # PostgreSQL Exporter
  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    restart: always
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:Admin*123@db:5432/ContactManagementDb?sslmode=disable"
    depends_on:
      - db
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

  # Worker Persistency
  worker-persistency:
    build:
      context: .
      dockerfile: src/TechChallenge-Postech-4NETT-FaseTres-Worker-Persistency.Job/Dockerfile
    container_name: contact_persistency_worker
    restart: always
    ports:
      - "5008:5008"
      - "5679:5679"
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "ContactManagementDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Admin*123"
    depends_on:
      - db
      - rabbitmq
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postech.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin*123"
    depends_on:
      - db
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Admin*123"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus"
    networks:
      techchallenge-postech-4nett-fasetres-worker-persistency_custom_network:
        ipv4_address: 192.168.80.6

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

  # cAdvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cAdvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

networks:
  techchallenge-postech-4nett-fasetres-worker-persistency_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/24
