global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'contact_integration_worker'
    static_configs:
      - targets: ['contact_integration_worker:5678']
        labels:
          app: 'contactintegration_app'

  - job_name: 'contact_worker_persistency'
    static_configs:
      - targets: ['contact_worker_persistency:5679']      
        labels:
          app: 'contactpersistency_app'

  - job_name: 'contactfind_api'
    static_configs:
      - targets: ['contactfind_api:5266']
        labels:
          app: 'contactfind_app'

  - job_name: 'dotnet_contactupdate_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['dotnet_contactupdate_app:5010']
        labels:
          app: 'contactupdate_app'

  - job_name: 'dotnet_contactdelete_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['dotnet_contactdelete_app:5013']
        labels:
          app: 'contactdelete_app'

  - job_name: 'addcontact_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['addcontact_app:5011']
        labels:
          app: 'contactadd_app'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          app: 'rabbitmq'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          app: 'cadvisor'
 
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          app: 'postgres'