global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'contact_integration_worker'
    static_configs:
      - targets: ['contact_integration_worker:5678']

  - job_name: 'contact_persistency_worker'
    static_configs:
      - targets: ['contact_persistency_worker:5679']      

  - job_name: 'contactfind_api'
    static_configs:
      - targets: ['contactfind-api:5266']

  - job_name: 'dotnet_contactupdate_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['dotnet_contactupdate_app:5010']
        labels:
          app: 'contactupdate_app'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          app: 'rabbitmq'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          app: 'cadvisor'
 
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  