{
 "title": "Tech Challenge - Contact Management",
 "description": "Dashboard de monitoramento para os microsserviços criados para a terceira fase do Tech Challenge.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info, namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"}, rabbitmq_cluster)"
    }
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" }
  ]
 },
 "panels": [
  {
   "title": "Microsserviço de Cadastro de Contatos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência HTTP POST (/contacts)",
     "type": "stat",
     "description": "Mede a latência do endpoint exposto pelo microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(http_request_duration_seconds_sum{app=\"contactadd_app\",code=\"200\",method=\"POST\"} / http_request_duration_seconds_count{app=\"contactadd_app\",method=\"POST\",code=\"200\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego HTTP POST (/contacts)",
     "type": "timeseries",
     "description": "Mede o tráfego de requisições por minuto para o endpoint exposto pelo microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactadd_app\"}[1m])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erros HTTP POST (/contacts)",
     "type": "timeseries",
     "description": "Mede a taxa de erros por minuto para o endpoint exposto pelo microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactadd_app\",code=~\"5..\"}[1m]) * 60 or rate(http_requests_received_total{app=\"contactadd_app\",code=~\"4..\"}[1m]) * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de CPU",
     "type": "timeseries",
     "description": "Mede a saturação de CPU do microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"addcontact_app\"}[1m])) by (container_label_com_docker_compose_service) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de Memória",
     "type": "timeseries",
     "description": "Mede a saturação de memória em megabytes do microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(container_memory_usage_bytes{name=\"addcontact_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego de Rede",
     "type": "timeseries",
     "description": "Mede o tráfego de rede (entrada e saída) em megabytes do microsserviço de cadastro de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "(sum(rate(container_network_receive_bytes_total{name=\"addcontact_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(container_network_transmit_bytes_total{name=\"addcontact_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Microsserviço de Atualização de Contatos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência HTTP PATCH (/contacts/{contactId})",
     "type": "stat",
     "description": "Mede a latência do endpoint exposto pelo microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(http_request_duration_seconds_sum{app=\"contactupdate_app\",code=\"202\"} / http_request_duration_seconds_count{app=\"contactupdate_app\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego HTTP PATCH (/contacts/{contactId})",
     "type": "timeseries",
     "description": "Mede o tráfego de requisições por minuto para o endpoint exposto pelo microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactupdate_app\"}[1m])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erros HTTP PATCH (/contacts/{contactId})",
     "type": "timeseries",
     "description": "Mede a taxa de erros por minuto para o endpoint exposto pelo microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactupdate_app\",code=~\"5..\"}[1m]) * 60 or rate(http_requests_received_total{app=\"contactupdate_app\",code=~\"4..\"}[1m]) * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de CPU",
     "type": "timeseries",
     "description": "Mede a saturação de CPU do microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"dotnet_contactupdate_app\",name=\"dotnet_contactupdate_app\"}[1m])) by (container_label_com_docker_compose_service) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de Memória",
     "type": "timeseries",
     "description": "Mede a saturação de memória em megabytes do microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(container_memory_usage_bytes{container_label_com_docker_compose_service=\"dotnet_contactupdate_app\",name=\"dotnet_contactupdate_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego de Rede",
     "type": "timeseries",
     "description": "Mede o tráfego de rede (entrada e saída) em megabytes do microsserviço de atualização de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "(sum(rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"dotnet_contactupdate_app\",name=\"dotnet_contactupdate_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"dotnet_contactupdate_app\",name=\"dotnet_contactupdate_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Microsserviço de Exclusão de Contatos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência HTTP DELETE (/contacts/{contactId})",
     "type": "stat",
     "description": "Mede a latência do endpoint exposto pelo microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(http_request_duration_seconds_sum{app=\"contactdelete_app\",code=\"202\",method=\"DELETE\"} / http_request_duration_seconds_count{app=\"contactdelete_app\",method=\"DELETE\",code=\"202\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego HTTP DELETE (/contacts/{contactId})",
     "type": "timeseries",
     "description": "Mede o tráfego de requisições por minuto para o endpoint exposto pelo microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactdelete_app\"}[1m])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erros HTTP DELETE (/contacts/{contactId})",
     "type": "timeseries",
     "description": "Mede a taxa de erros por minuto para o endpoint exposto pelo microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactdelete_app\",code=~\"5..\"}[1m]) * 60 or rate(http_requests_received_total{app=\"contactdelete_app\",code=~\"4..\"}[1m]) * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de CPU",
     "type": "timeseries",
     "description": "Mede a saturação de CPU do microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"dotnet_contactdelete_app\"}[1m])) by (container_label_com_docker_compose_service) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de Memória",
     "type": "timeseries",
     "description": "Mede a saturação de memória em megabytes do microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(container_memory_usage_bytes{name=\"dotnet_contactdelete_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego de Rede",
     "type": "timeseries",
     "description": "Mede o tráfego de rede (entrada e saída) em megabytes do microsserviço de exclusão de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "(sum(rate(container_network_receive_bytes_total{name=\"dotnet_contactdelete_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(container_network_transmit_bytes_total{name=\"dotnet_contactdelete_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Microsserviço de Consulta de Contatos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência HTTP GET (/contacts)",
     "type": "stat",
     "description": "Mede a latência do endpoint exposto pelo microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(http_request_duration_seconds_sum{app=\"contactfind_app\",code=\"200\",method=\"GET\"} / http_request_duration_seconds_count{app=\"contactfind_app\",method=\"GET\",code=\"200\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego HTTP GET (/contacts)",
     "type": "timeseries",
     "description": "Mede o tráfego de requisições por minuto para o endpoint exposto pelo microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactfind_app\"}[1m])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erros HTTP GET (/contacts)",
     "type": "timeseries",
     "description": "Mede a taxa de erros por minuto para o endpoint exposto pelo microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{app=\"contactfind_app\",code=~\"5..\"}[1m]) * 60 or rate(http_requests_received_total{app=\"contactfind_app\",code=~\"4..\"}[1m]) * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de CPU",
     "type": "timeseries",
     "description": "Mede a saturação de CPU do microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"contactfind_api\"}[1m])) by (container_label_com_docker_compose_service) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Saturação de Memória",
     "type": "timeseries",
     "description": "Mede a saturação de memória em megabytes do microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "(sum(rate(container_memory_usage_bytes{name=\"contactfind_api\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tráfego de Rede",
     "type": "timeseries",
     "description": "Mede o tráfego de rede (entrada e saída) em megabytes do microsserviço de consulta de contatos.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "(sum(rate(container_network_receive_bytes_total{name=\"addcontact_app\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(container_network_transmit_bytes_total{name=\"contactfind_api\"}[1m])) by (container_label_com_docker_compose_service) / 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mensagens prontas ",
     "type": "stat",
     "description": "Mede a quantidade de mensagens prontas nas filas RabbitMQ criadas para os microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
      }
     ]
    },
    {
     "title": "Mensagens recebidas por segundo",
     "type": "stat",
     "description": "Mede a quantidade de mensagens recebidas por segundo nas filas RabbitMQ criadas para os microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
      }
     ]
    },
    {
     "title": "Publicadores",
     "type": "stat",
     "description": "Mede a quantidade de publicadores existentes na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_global_publishers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
      }
     ]
    },
    {
     "title": "Conexões",
     "type": "stat",
     "description": "Mede a quantidade de conexões ativas na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_connections * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
      }
     ]
    },
    {
     "title": "Filas",
     "type": "stat",
     "description": "Mede a quantidade de filas na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queues * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
      }
     ]
    },
    {
     "title": "Mensagens não confirmadas",
     "type": "stat",
     "description": "Mede a quantidade de mensagens não confirmadas nas filas RabbitMQ criadas para os microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacked * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Mensagens enviadas por segundo",
     "type": "stat",
     "description": "Mede a quantidade de mensagens enviadas por segundo nas filas RabbitMQ criadas para os microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_auto_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_manual_ack_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Consumidores",
     "type": "stat",
     "description": "Mede a quantidade de consumidores existentes na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_consumers * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Canais",
     "type": "stat",
     "description": "Mede a quantidade de canais existentes na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_channels * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Nós",
     "type": "stat",
     "description": "Mede a quantidade de nós existentes na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_build_info * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total de conexões",
     "type": "timeseries",
     "description": "Mede o número total de conexões na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_connections * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Conexões abertas por segundo",
     "type": "timeseries",
     "description": "Mede a quantidade de conexões abertas por segundo na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_connections_opened_total[60s]) * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Conexões fechados por segundo",
     "type": "timeseries",
     "description": "Mede a quantidade de conexões fechadas por segundo na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_connections_closed_total[60s]) * on(instance, job) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Versão",
     "type": "stat",
     "description": "Exibe a versão instalada do PostgreSQL na infraestrutura de microsserviços de gerenciamento de contatos",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "pg_static", "legendFormat": "{{short_version}}" }
     ]
    },
    {
     "title": "Horário de inicialização",
     "type": "stat",
     "description": "Exibe o horário de inicialização da instância do PostgreSQL na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_postmaster_start_time_seconds * 1000"
      }
     ]
    },
    {
     "title": "Dados de busca atuais",
     "type": "stat",
     "description": "Mede a quantidade de dados buscados na instância PostgreSQL da infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\"})"
      }
     ]
    },
    {
     "title": "Dados de inserção atuais",
     "type": "stat",
     "description": "Mede a quantidade de dados inseridos na instância PostgreSQL da infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\"})"
      }
     ]
    },
    {
     "title": "Dados de atualização atuais",
     "type": "stat",
     "description": "Mede a quantidade de dados atualizados na instância PostgreSQL da infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\"})"
      }
     ]
    },
    {
     "title": "Conexões máximas",
     "type": "stat",
     "description": "Exibe a quantidade máxima de conexões do PostgreSQL na infraestrutura de microsserviços de gerenciamento de contatos",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "pg_settings_max_connections" }
     ]
    },
    {
     "title": "Uso médio de CPU",
     "type": "timeseries",
     "description": "Tempo médio de CPU gasto pelo usuário e pelo sistema PostgreSQL em segundos na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Uso médio de memória",
     "type": "timeseries",
     "description": "Tempo médio de memória gasto pelo usuário e pelo sistema PostgreSQL em segundos na infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Mede a quantidade de descritores de arquivo abertos na instância PostgreSQL da infraestrutura de microsserviços de gerenciamento de contatos.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "process_open_fds", "legendFormat": "Open FD" }
     ]
    }
   ]
  }
 ]
}