apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
data:
  POSTGRES_DB: Q29udGFjdE1hbmFnZW1lbnREYg== 
  POSTGRES_USER: YWRtaW4=               
  POSTGRES_PASSWORD: ZzNaY0FVS2I=
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AcG9zdGVjaC5jb20=
  PGADMIN_DEFAULT_PASSWORD: QWRtaW4qMTIz
  DATA_SOURCE_NAME: cG9zdGdyZXNxbDovL2FkbWluOmczWmNBVUtiQHNlcnZpY2UtcG9zdGdyZXMtZGI6NTQzMi9Db250YWN0TWFuYWdlbWVudERiP3NzbG1vZGU9ZGlzYWJsZQ==
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-db-pv
  labels:
    name: postgres-db-pv
spec:
  capacity: 
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  labels:
    name: postgres-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
      annotations:
        prometheus.io/scrape: "true" 
        prometheus.io/path: "/metrics" 
        prometheus.io/port: "9187" 
    spec:
      containers:
        - name: container-postgres-db
          image: lruizd/techchallenge-postgres-db:v1
          ports:
            - name: "db-port"
              containerPort: 5432
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT * FROM contacts.tb_area_code LIMIT 1;" || exit 1
            initialDelaySeconds: 20
            periodSeconds: 20
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db-storage
        - name: container-pgadmin
          image: dpage/pgadmin4
          ports:
            - name: "admin-port"
              containerPort: 5050
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: PGADMIN_DEFAULT_PASSWORD
        - name: container-postgres-exporter
          image: wrouesnel/postgres_exporter:latest
          ports:
            - name: "exporter-port"
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: DATA_SOURCE_NAME
      volumes:
        - name: postgres-db-storage
          persistentVolumeClaim:
            claimName: postgres-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-postgres-db
  labels:
    app: postgres-db
spec:
  type: NodePort
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
    - name: admin-port
      port: 80
      targetPort: 80
      nodePort: 31194
    - name: exporter-port
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-db