apiVersion: v1
kind: Secret
metadata:
  name: techchallenge-dotnet-contactpersistency-secret
type: Opaque
data:
  RABBITMQ_HOST: c2VydmljZS1yYWJiaXRtcQ==
  RABBITMQ_PORT: NTY3Mg==
  POSTGRES_HOST: c2VydmljZS1wb3N0Z3Jlcy1kYg==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_DB: Q29udGFjdE1hbmFnZW1lbnREYg==
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: ZzNaY0FVS2I=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactpersistency
  labels:
    app: techchallenge-dotnet-contactpersistency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactpersistency
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactpersistency
      annotations:
        prometheus.io/scrape: "true" 
        prometheus.io/path: "/metrics" 
        prometheus.io/port: "5679" 
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactpersistency
          image: lruizd/techchallenge-dotnet-contactpersistency:latest
          ports:
            - containerPort: 5679
          env:
            - name: RABBITMQ_HOST
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: RABBITMQ_PORT
            - name: POSTGRES_HOST
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: techchallenge-dotnet-contactpersistency-secret
                  key: POSTGRES_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactpersistency
  labels:
    app: techchallenge-dotnet-contactpersistency
spec:
  type: ClusterIP
  ports:
    - port: 5679
      targetPort: 5679
  selector:
    app: techchallenge-dotnet-contactpersistency