-- Cria o schema 'contacts' se não existir
CREATE SCHEMA IF NOT EXISTS contacts;

-- Cria a tabela tb_region se não existir
CREATE TABLE IF NOT EXISTS contacts.tb_region (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(12) NOT NULL,
    state_name VARCHAR(19) NOT NULL
);

-- Cria a tabela tb_area_code se não existir
CREATE TABLE IF NOT EXISTS contacts.tb_area_code (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value CHAR(2) NOT NULL,
    region_id SMALLINT NOT NULL,
    CONSTRAINT fk_tb_region_tb_area_code FOREIGN KEY (region_id) REFERENCES contacts.tb_region (id) ON DELETE CASCADE
);

-- Cria a tabela tb_contact_phone se não existir
CREATE TABLE IF NOT EXISTS contacts.tb_contact_phone (
    id SERIAL PRIMARY KEY,
    number VARCHAR(9) NOT NULL,
    area_code_id SMALLINT NOT NULL,
    CONSTRAINT fk_tb_area_code_tb_contact_phone FOREIGN KEY (area_code_id) REFERENCES contacts.tb_area_code (id) ON DELETE CASCADE
);

-- Cria a tabela tb_contact se não existir
CREATE TABLE IF NOT EXISTS contacts.tb_contact (
    id UUID PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    contact_phone_area_code SMALLINT NOT NULL,
    contact_phone INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT TRUE
);
